# Generated by Django 4.1.1 on 2022-09-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='matches')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.match')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
        migrations.DeleteModel(
            name='GamePlayer',
        ),
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.game'),
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ManyToManyField(to='Game.player'),
        ),
    ]
