# Generated by Django 4.1.1 on 2022-09-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_match_matchplayer_stream_remove_game_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player',
        ),
    ]
