# Generated by Django 4.1.1 on 2022-09-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_remove_match_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matches'),
        ),
    ]
