# Generated by Django 4.1.1 on 2022-09-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_match_stadium_alter_match_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_winner', models.CharField(max_length=250)),
                ('silver_winner', models.CharField(max_length=250)),
                ('bronze_winner', models.CharField(max_length=250)),
                ('descriptiom', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.match')),
            ],
        ),
    ]
