# Generated by Django 4.1.1 on 2022-09-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_matchsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchsummary',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
