# Generated by Django 4.1.1 on 2022-09-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_player_medals_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='streams'),
        ),
    ]
