# Generated by Django 4.1.1 on 2022-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_stream_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
