# Generated by Django 4.1.1 on 2022-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0011_stream_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stream_videos'),
        ),
    ]
