# Generated by Django 4.1.1 on 2022-09-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_stream_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='url',
        ),
    ]
