# Generated by Django 4.1.1 on 2022-09-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0013_remove_stream_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
