# Generated by Django 4.1.1 on 2022-09-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0014_delete_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
