# Generated by Django 4.1.1 on 2022-09-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0015_comment_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visits',
        ),
        migrations.AddField(
            model_name='stream',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
