# Generated by Django 4.1.1 on 2022-09-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0016_remove_comment_visits_stream_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news')),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
